"""add spin columns

Revision ID: 35c120a4f308
Revises: ffa8485dd451
Create Date: 2025-12-19 11:42:35.874403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35c120a4f308'
down_revision = 'ffa8485dd451'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spin_chances', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('spin_chances')

    # ### end Alembic commands ###
