"""Ajout de last_spin_gain dans User

Revision ID: 45d2e9717c18
Revises: 35c120a4f308
Create Date: 2025-12-20 08:17:41.960346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45d2e9717c18'
down_revision = '35c120a4f308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_spin_gain', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_spin_gain')

    # ### end Alembic commands ###
