"""Initial tables

Revision ID: ffa8485dd451
Revises: 
Create Date: 2025-12-12 06:25:17.138924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffa8485dd451'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parrain_phone', sa.String(length=30), nullable=True),
    sa.Column('filleul_phone', sa.String(length=30), nullable=True),
    sa.Column('montant', sa.Float(), nullable=True),
    sa.Column('niveau', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('depot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('montant', sa.Float(), nullable=True),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investissement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('montant', sa.Float(), nullable=True),
    sa.Column('revenu_journalier', sa.Float(), nullable=True),
    sa.Column('duree', sa.Integer(), nullable=True),
    sa.Column('date_debut', sa.DateTime(), nullable=True),
    sa.Column('dernier_paiement', sa.DateTime(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retrait',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('montant', sa.Float(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('vip_level', sa.String(length=20), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('duree', sa.Integer(), nullable=True),
    sa.Column('taux_min', sa.Float(), nullable=True),
    sa.Column('taux_max', sa.Float(), nullable=True),
    sa.Column('revenu_total', sa.Float(), nullable=False),
    sa.Column('date_debut', sa.DateTime(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('parrain', sa.String(length=30), nullable=True),
    sa.Column('commission_total', sa.Float(), nullable=True),
    sa.Column('wallet_country', sa.String(length=50), nullable=True),
    sa.Column('wallet_operator', sa.String(length=50), nullable=True),
    sa.Column('wallet_number', sa.String(length=30), nullable=True),
    sa.Column('solde_total', sa.Float(), nullable=True),
    sa.Column('solde_depot', sa.Float(), nullable=True),
    sa.Column('solde_parrainage', sa.Float(), nullable=True),
    sa.Column('solde_revenu', sa.Float(), nullable=True),
    sa.Column('premier_depot', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('uid')
    )
    op.create_table('vlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('montant', sa.Float(), nullable=True),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vlog')
    op.drop_table('user')
    op.drop_table('staking')
    op.drop_table('retrait')
    op.drop_table('investissement')
    op.drop_table('depot')
    op.drop_table('commission')
    # ### end Alembic commands ###
